version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: untitled7-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - untitled7-network

  api:
    build: ./api
    container_name: untitled7-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3001
#      - HOST=http://drampi-untitled7.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - untitled7-network

  auth:
    build: ./auth
    container_name: untitled7-auth
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
#      - HOST=http://drampi-untitled7.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - untitled7-network

  api_db:
    image: library/mongo:latest
    container_name: untitled7-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - untitled7-network

  auth_db:
    image: library/mongo:latest
    container_name: untitled7-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - untitled7-network

  nginx:
    image: nginx:stable-alpine
    container_name: untitled7-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod/:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - untitled7-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  untitled7-network:
    driver: bridge
